# https://jekyllrb.com/docs/configuration/default

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "src/",
  "./*.json",
  "./*.js"
]

data_dir: data

collections:
  authors:
    output: true
